name: Release
on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        id: build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          #name: firefox-aws-apps-container.xpi
          path: ${{ steps.build.outputs.target }}

      - name: Sign
        id: sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.sign.outputs.target }}
